//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcoleRepo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cours
    {
        public Cours()
        {
            this.PresenceCours = new HashSet<PresenceCours>();
        }
    
        public int CoursId { get; set; }
        public System.DateTime DateDebut { get; set; }
        public System.DateTime DateFin { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<PresenceCours> PresenceCours { get; set; }
        public virtual Matiere Matiere { get; set; }
        public virtual Enseignant Enseignant { get; set; }
    }
}
