//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcoleRepo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EcoleContainer : DbContext
    {
        public EcoleContainer()
            : base("name=EcoleContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Personne> Personnes { get; set; }
        public virtual DbSet<PresenceCours> PresenceCours { get; set; }
        public virtual DbSet<Cours> Cours { get; set; }
        public virtual DbSet<Matiere> Matieres { get; set; }
        public virtual DbSet<TypeEvaluation> TypeEvaluations { get; set; }
        public virtual DbSet<Evaluation> Evaluations { get; set; }
    }
}
