//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcoleRepo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Matiere
    {
        public Matiere()
        {
            this.Cours = new HashSet<Cours>();
            this.Evaluations = new HashSet<Evaluation>();
        }
    
        public int MatiereId { get; set; }
        public string Titre { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Cours> Cours { get; set; }
        public virtual ICollection<Evaluation> Evaluations { get; set; }
    }
}
