//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcoleRepo
{
    using System;
    using System.Collections.Generic;
    
    public partial class PresenceCours
    {
        public int EtudiantId { get; set; }
        public int CoursId { get; set; }
        public string Motif { get; set; }
        public bool Absence { get; set; }
    
        public virtual Etudiant Etudiant { get; set; }
        public virtual Cours Cours { get; set; }
    }
}
