//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcoleRepo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypeEvaluation
    {
        public TypeEvaluation()
        {
            this.Evaluations = new HashSet<Evaluation>();
        }
    
        public int TypeEvaluationId { get; set; }
        public string Type { get; set; }
        public decimal Ponderation { get; set; }
    
        public virtual ICollection<Evaluation> Evaluations { get; set; }
    }
}
